project_name: io_blaster
env:
  - GO111MODULE=on
  - GOPROXY=goproxy.devops.iguazeng.com
before:
  hooks:
    - go mod download
builds:
  - id: io_blaster
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: io_blaster
    ldflags:
      - -s -w -X main.AppVersion={{ .Version }}
  - id: io_blaster_latest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    binary: io_blaster
    ldflags:
      - -s -w -X main.AppVersion={{ .Version }}
archives:
  - id: io_blaster
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: binary
    replacements:
      amd64: x86_64
    builds:
      - io_blaster
    allow_different_binary_count: true
  - id: io_blaster_latest
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: binary
    replacements:
      amd64: x86_64
    builds:
      - io_blaster_latest
    allow_different_binary_count: true
release:
  ids:
    - io_blaster
artifactories:
  - name: iguazio
    target: https://artifactory.iguazeng.com/artifactory/iguazio_naipi/{{ .ProjectName }}/{{ .Version }}/
    mode: binary
    checksum: true
    ids:
      - io_blaster
  - name: naipi
    target: https://artifactory.iguazeng.com/artifactory/iguazio_naipi/{{ .ProjectName }}/
    mode: binary
    checksum: true
    ids:
      - io_blaster_latest
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
  disable: false
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
